CREATE TABLE departamento (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(255)
);

CREATE TABLE funcionario (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100),
	departamento_id INTEGER NOT NULL,
	FOREIGN KEY (departamento_id) REFERENCES departamento(id) ON DELETE CASCADE
);

